[package]
name = "fix_messages_example"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
fefix = { version="0.7.0", features=["full"]}

[build-dependencies]
fefix = { version="0.7.0", features = ["codegen"]}

[features]
sofh_big_endian = []
